// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbxDsu79rx2jiZ1pShDw7gQXVfdjuDnk4',
    appId: '1:630131460071:web:bc356dcf51397442e0df42',
    messagingSenderId: '630131460071',
    projectId: 'flutter-firebase-project-74c56',
    authDomain: 'flutter-firebase-project-74c56.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-74c56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD136rgbD6v3diuCDFd0jzn5A9extjJGqM',
    appId: '1:630131460071:android:277612c1a350f167e0df42',
    messagingSenderId: '630131460071',
    projectId: 'flutter-firebase-project-74c56',
    storageBucket: 'flutter-firebase-project-74c56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQNrq3JokBNt1agTebnwR1RrqB68vXcCI',
    appId: '1:630131460071:ios:54c2b11c25832453e0df42',
    messagingSenderId: '630131460071',
    projectId: 'flutter-firebase-project-74c56',
    storageBucket: 'flutter-firebase-project-74c56.appspot.com',
    iosClientId: '630131460071-uvp72d8kh28jbgv7045l5k61b0fe0qsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFirebaseAuth1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQNrq3JokBNt1agTebnwR1RrqB68vXcCI',
    appId: '1:630131460071:ios:54c2b11c25832453e0df42',
    messagingSenderId: '630131460071',
    projectId: 'flutter-firebase-project-74c56',
    storageBucket: 'flutter-firebase-project-74c56.appspot.com',
    iosClientId: '630131460071-uvp72d8kh28jbgv7045l5k61b0fe0qsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFirebaseAuth1',
  );
}
